pub const syllables = [_][]const u8{
    "at",  "ap",  "ay",  "ak",  "aq",  "ar",  "ab",  "am",
    "it",  "ip",  "iy",  "ik",  "iq",  "ir",  "ib",  "im",
    "ut",  "up",  "uy",  "uk",  "uq",  "ur",  "ub",  "um",
    "et",  "ep",  "ey",  "ek",  "eq",  "er",  "eb",  "em",
    "ot",  "op",  "oy",  "ok",  "oq",  "or",  "ob",  "om",
    "na",  "ka",  "kra", "kza", "tsa", "tza", "rya", "psa",
    "ni",  "ki",  "kri", "kzi", "tsi", "tzi", "ryi", "psi",
    "nu",  "ku",  "kru", "kzu", "tsu", "tzu", "ryu", "psu",
    "ne",  "ke",  "kre", "kze", "tse", "tze", "rye", "pse",
    "no",  "ko",  "kro", "kzo", "tso", "tzo", "ryo", "psa",
    "qta", "qua", "tka", "hya", "hua", "pha", "rza", "dza",
    "qti", "qui", "tki", "hyi", "hui", "phi", "rzi", "dzi",
    "qtu", "quu", "tku", "hyu", "huu", "phu", "rzu", "dzu",
    "qte", "que", "tke", "hye", "hue", "phe", "rze", "dze",
    "qto", "quo", "tko", "hyo", "huo", "pho", "rzo", "dzo",
};
